version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    group_add:
      - "989"
    network_mode: 'host'
    # ports:
    #   - 7359:7359/udp
    volumes:
      - /jellyfin/config:/config
      - /jellyfin/cache:/cache
      - /mnt/cupcake/Music:/Music
      - /mnt/cupcake/Pictures:/Pictures
      - /mnt/chonk/media/TVShows:/TVShows
      - /mnt/chonk/media/Films:/Films
      - /mnt/chonk/media/Videos:/Videos
      - /mnt/chonk/media/Books:/Books
    devices:
      # VAAPI Devices (examples)
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/card1:/dev/dri/card1
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/renderD129:/dev/dri/renderD129
    restart: 'unless-stopped'
    deploy:
     resources:
       reservations:
         devices:
           - capabilities: [gpu]
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=http://skyline-im9xwdzjyj.ddns.net:8096
